name: ${pom.name}
version: ${pom.version}
website: ${pom.url}
author: captbunzo

main: net.nyvaria.fasttravel.FastTravel

commands:
  goto:
    description: This is the goto command (formerly /teleport).
    usage: /<command> [player]
  
  call:
    description: This is the call command (formerly /summon).
    usage: /<command> [player]
  
  clearrequests:
    description: This is the clearrequests command.
    usage: /<command> [player]
    permission: <plugin name>.request.clearall
    permission-message: You don't have <permission>

permissions:
  fasttravel.*:
    description: Gives access to all FastTravel commands
    children:
      fasttravel.goto:          true
      fasttravel.call:          true
      fasttravel.clearrequests: true
    
  fasttravel.request.goto:
    description: Allows you to initiate a goto (teleport) request
    default: op
    
  fasttravel.request.call:
    description: Allows you to call initiate a call (summon) request
    default: op
    
  fasttravel.request.clearall:
    description: Allows you to clear all existing requests
    default: op
