name: ${pom.name}
version: ${pom.version}
website: ${pom.url}
author: captbunzo

main: net.nyvaria.fasttravel.FastTravel

commands:
  invite:
    description: This is the invite command (formerly /summon).
    usage: /<command> [player]
  
  visit:
    description: This is the visit command (formerly /teleport).
    usage: /<command> [player]
  
  clearrequests:
    description: This is the clearrequests command.
    usage: /<command> [player]
    permission: <plugin name>.request.clearall
    permission-message: You don't have <permission>

permissions:
  fasttravel.*:
    description: Gives access to all FastTravel commands
    children:
      fasttravel.invite:        true
      fasttravel.visit:         true
      fasttravel.clearrequests: true
    
  fasttravel.request.visit:
    description: Allows you to request to visit someone
    default: op
    
  fasttravel.request.invite:
    description: Allows you to extend an invitation to another player to visit
    default: op
    
  fasttravel.request.clearall:
    description: Allows you to clear all existing requests
    default: op
